name: "Test"

base:
    exp: 'exp'
    tensorboard: 'tensorboard'
    wandb: 'wandb'
    neptune: 'neptune'
    seed: 777

trainer:
    accelerator: 'ddp'
    accumulate_grad_batches: 1
    amp_backend: 'native' # 'native' 'apex'
    max_epochs: 100
    min_epochs: 5
    amp_level: 'O1'
    auto_lr_find: false
    auto_scale_batch_size: false
    auto_select_gpus: false
    benchmark: false
    fast_dev_run: false
    flush_logs_every_n_steps: 100
    gpus: ???
    gradient_clip_val: 50
    gradient_clip_algorithm: 'norm'
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    limit_predict_batches: 1.0
    log_every_n_steps: 5
    prepare_data_per_node: false 
    precision: 32
    replace_sampler_ddp: true
    resume_from_checkpoint: null

module:
    select: "mobilenet"
    conf:
        init:
            select: 'nn.init.kaiming_uniform_' # 'nn.init.xavier_normal_' 'nn.init.xavier_uniform_' 'nn.init.kaiming_uniform_' 'nn.init.kaiming_normal_'
        af:
            fs: 16000
        frontend:
            fft:
                n_fft: 512
                hop_length: 400
            agc:
                select: 'DummyGAIN'
                conf:

loss:
    select: "MASK_DTD_LOSS"
    conf:
        criterion_DTD: "nn.CrossEntropyLoss"
        criterion_mask: "nn.BCELoss"
        DTDweight: 0.3
        real_mask_clip: true

optim:
    optim:
        contiguous_params: false # unavailable currently
        select: "optim.Adam" # 'optim.Adam' 'optim.SGD'
        conf:
            lr: 0.001
    scheduler:
        select: "lambdalr"
        conf:
           last_epoch: -1 
           lr_lambda: 'lambda epoch: 0.95 ** epoch'

data:
    data_loader:
        train:
            batch_size: 1
            shuffle: false
            num_workers: 0
        val:
            batch_size: 1
            shuffle: false
            num_workers: 0
        test:
            batch_size: 1
            shuffle: false
            num_workers: 0
    dataset:
        train: 
            - select: "AECC_SYNTHETIC_DATASET"
              conf:
                  path: "/data1/tanghaoyu/AEC-Challenge/datasets/synthetic"
                  split: 'train'
                  check: false
                  scale: false
        val:
            - select: "AECC_SYNTHETIC_DATASET"
              conf:
                  path: "/data1/tanghaoyu/AEC-Challenge/datasets/synthetic"
                  split: 'test'
                  check: false
                  scale: true
        test:
            - select: "AECC_REAL_DATASET"
              conf:
                  path: "/data1/tanghaoyu/AEC-Challenge/datasets/blind_test_set/noisy"
                  dump_path: "test_test_noisy.list"
                  check: false

callbacks:
    progressbar: true
    progressbar_conf:
        refresh_rate: 1
        process_position: 0
    modelcheckpoint: true
    modelcheckpoint_conf:
        filename: 'epoch{epoch}-val_loss{val_total:.2f}' 
        monitor: 'val_total'
        save_last: true
        save_top_k: 5
        dirpath: '${base.exp}/${name}'
    earlystopping: true
    earlystopping_conf:
        monitor: 'val_total'
        mode: 'max'
        min_delta: 0.001
        patience: 5
    gpu_stats: false
    gpu_stats_conf:
        memory_utilization: true
        gpu_utilization: true
    lr_monitor: true
    lr_monitor_conf:
        logging_interval: 'epoch'

loggers:
    tensorboard: false
    tensorboard_conf:
        'save_dir': '${base.tensorboard}/${name}'
    wandb: false
    wandb_conf:
        name: ${name}
        save_dir: '${base.wandb}'
        project: 'raaec'
        log_model: true
    neptune: false
    neptune_conf:
        project_name: '${base.neptune}'
        experiment_name: '${name}'
        api_token: 'ANONYMOUS'

logging:
    level: 'INFO' 
